### PR TITLE
Types: Allow watching multiple files

### PR DESCRIPTION
**Pull request by Gnuk**

### CODE REVIEW

**Comment by Gnuk** [comment]
Hi @yuanchuan I don't know why threre is those errors because I never changed any implementation. I also don't know why the package-lock.json is not tracked.

**Comment by yuanchuan** [comment]
Hi @Gnuk 

The errors are OK, which are caused by timers. `node-watch` is dependency-free so I removed it.

**Comment by yuanchuan** [comment]
Hmm.. currently `node-watch` can handle the following input:

```js
watch([['./a', './b'], './c']])
```
Does this Type match it too?

```typescript
Filename = string | string[]
```

**Comment by Gnuk** [comment]
Effectively, TS don't allow Type Recursion, I can put `string | any[]` but it's not optimal :s

**Comment by Gnuk** [comment]
In fact interfaces allow recursion so I pushed my new idea.

**Comment by Gnuk** [comment]
Hi @yuanchuan , in fact interfaces allow recursion so I pushed my new idea.

**Comment by yuanchuan** [comment]
Merged, thanks!

**Pull request merged**
