### PR TITLE
Updating to latest version of node; adding linting and coverage reports

### PR DESCRIPTION
**Pull request by intervalia**
Updated repos and added eslint
* Added node version 10 and 11 to travis.yml. Also removed versions 4 and 5 since they are no longer supported. (Also updated fs-extra from 1.0.0 to 7.0.0 which also dropped support for Node 4 and 5) - If you still want node 4 and 5 support we would need to go to version 5.0.0 of `fs-estra`.
* Removed `./index.js` and changed `package.json` to point to `./lib/watch.js` as main, thus reducing code. Less to load and less to process.
* Simplified `Buffer` creation in test.js
* Removed un-needed `'utf8'` string. In all cases `'utf8'` was teh default, thus not needed.
* Added `package-lock.json` file
* Removed unneeded `else` statements (When the `if` uses return, then no else is needed.)
* `npm test` still only runs mocha tests.
* `npm run lint` will run eslint. Eslint also works in editors/
* `npm run test-all` that will run eslint and run mocha tests with coverage reporting through `nyc`.
* Added .eslintrs file and eslint to the repo
* Changed all == to === for linting (With the exception of `(item == null)` which checks for both `null` and `undefined`
* Added `.coverage/` and `.nyc_output/` to `.gitignore` file.

### CODE REVIEW

**Comment by intervalia** [comment]
Also your tests are a little skiddish and fail sometimes due to timing issues. I was going to look at that and ran out of time. I can look at them in the future if you want.

**Comment by intervalia** [comment]
If you restart the failed test it will likely pass. This is what I was seeing. Some tests fail, then you restart them and they pass.

**Comment by yuanchuan** [comment]
Really appreciated it. This repo hasn't any activity for some time now.  

Some tests failed may be due to the default 100ms debounce delay. It is so for my laptop at least, using 200ms is fine IMO.

**Comment by intervalia** [comment]
You may want to change the major number since this is a breaking chance for
anyone using node 4 or 5.

**Comment by yuanchuan** [comment]
I'll use 0.6.0 for the next release.

**Comment by intervalia** [comment]
Are you ok if I look for more optimizations?  If you drop node 4 and 5 then
I can update it to use more ES6 code and probably reduce the code size

**Comment by intervalia** [comment]
Sure. I have several ideas. I would love to see two versions of this.

1) That is a 100% drop-in replacement for fs-watch, but with recursive
working with Linux. But ZERO other features. (Small and fast) - Most of the
time I would use this one.
2) The version you have now, maybe with even more enhancements. Better
globby support, etc.

I can create the PRs and let you decide if you want them or not.

Mike

**Comment by yuanchuan** [comment]
Great!

I've added you to Github and NPM.

**Comment by intervalia** [comment]
Thanks

**Pull request merged**
